server:
  port: 8080
  servlet:
    context-path: /migrosApi

spring:
  application:
    name: courier

  main:
    web-application-type: servlet

  datasource:
    url: jdbc:postgresql://localhost:5332/courier
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    enabled: true